version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    target-branch: master
    groups:
      cargo-minor-patch:
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /crates/markplane-web/ui
    schedule:
      interval: weekly
    target-branch: master
    groups:
      npm-minor-patch:
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 10
