use std::collections::HashSet;
use std::fs;

use chrono::Local;

use crate::error::Result;
use crate::models::*;
use crate::project::{Project, find_blocked_items};
use crate::query::QueryFilter;

const GENERATED_HEADER: &str = "<!-- Generated by markplane sync -->";

impl Project {
    /// Generate .context/summary.md (~1000 tokens target)
    pub fn generate_context_summary(&self) -> Result<()> {
        let config = self.load_config()?;
        let now = Local::now().format("%Y-%m-%d").to_string();
        let recent_days = config.context.recent_days;

        let backlog_items = self.list_backlog_items(&QueryFilter::default())?;
        let epics = self.list_epics()?;
        let plans = self.list_plans()?;

        let mut content = format!(
            "{}\n# Project: {}\n\n",
            GENERATED_HEADER, config.project.name
        );

        // Active epics with progress
        let active_epics: Vec<_> = epics
            .iter()
            .filter(|e| e.frontmatter.status == EpicStatus::Active)
            .collect();
        if !active_epics.is_empty() {
            content.push_str("## Active Epics\n");
            for epic in &active_epics {
                let epic_items: Vec<_> = backlog_items
                    .iter()
                    .filter(|i| i.frontmatter.epic.as_deref() == Some(&epic.frontmatter.id))
                    .collect();
                let total = epic_items.len();
                let done = epic_items
                    .iter()
                    .filter(|i| i.frontmatter.status == BacklogStatus::Done)
                    .count();
                let remaining = total - done;
                let pct = if total > 0 {
                    (done as f64 / total as f64 * 100.0) as u32
                } else {
                    0
                };
                content.push_str(&format!(
                    "- {}: {} ({}% complete, {} items remaining)\n",
                    epic.frontmatter.id, epic.frontmatter.title, pct, remaining
                ));
            }
            content.push('\n');
        }

        // In-progress work
        let in_progress: Vec<_> = backlog_items
            .iter()
            .filter(|i| i.frontmatter.status == BacklogStatus::InProgress)
            .collect();
        if !in_progress.is_empty() {
            content.push_str("## In-Progress Work\n");
            for item in &in_progress {
                let assignee_str = item
                    .frontmatter
                    .assignee
                    .as_ref()
                    .map(|a| format!(", @{}", a))
                    .unwrap_or_default();
                content.push_str(&format!(
                    "- {}: {} ({}{})\n",
                    item.frontmatter.id, item.frontmatter.title, item.frontmatter.priority, assignee_str
                ));
            }
            // Also show in-progress plans
            let active_plans: Vec<_> = plans
                .iter()
                .filter(|p| p.frontmatter.status == PlanStatus::InProgress)
                .collect();
            for plan in &active_plans {
                content.push_str(&format!(
                    "- {}: {} (plan)\n",
                    plan.frontmatter.id, plan.frontmatter.title
                ));
            }
            content.push('\n');
        }

        // Blocked items (items whose depends_on contains items that aren't done)
        let done_ids: HashSet<&str> = backlog_items
            .iter()
            .filter(|i| i.frontmatter.status == BacklogStatus::Done)
            .map(|i| i.frontmatter.id.as_str())
            .collect();
        let blocked = find_blocked_items(&backlog_items);
        if !blocked.is_empty() {
            content.push_str("## Blocked Items\n");
            for item in &blocked {
                let blockers: Vec<_> = item
                    .frontmatter
                    .depends_on
                    .iter()
                    .filter(|dep| !done_ids.contains(dep.as_str()))
                    .collect();
                content.push_str(&format!(
                    "- {}: {} (blocked by {})\n",
                    item.frontmatter.id,
                    item.frontmatter.title,
                    blockers
                        .iter()
                        .map(|s| s.as_str())
                        .collect::<Vec<_>>()
                        .join(", ")
                ));
            }
            content.push('\n');
        }

        // Recent completions
        let today = Local::now().date_naive();
        let cutoff = today - chrono::Duration::days(recent_days as i64);
        let recent_done: Vec<_> = backlog_items
            .iter()
            .filter(|i| i.frontmatter.status == BacklogStatus::Done && i.frontmatter.updated >= cutoff)
            .collect();
        if !recent_done.is_empty() {
            content.push_str(&format!(
                "## Recent Completions (last {} days)\n",
                recent_days
            ));
            for item in &recent_done {
                content.push_str(&format!(
                    "- {}: {} (done {})\n",
                    item.frontmatter.id, item.frontmatter.title, item.frontmatter.updated
                ));
            }
            content.push('\n');
        }

        // Priority queue (next items: planned/backlog, sorted by priority)
        let next_up: Vec<_> = backlog_items
            .iter()
            .filter(|i| {
                i.frontmatter.status == BacklogStatus::Planned
                    || i.frontmatter.status == BacklogStatus::Backlog
            })
            .take(5)
            .collect();
        if !next_up.is_empty() {
            content.push_str("## Priority Queue (next up)\n");
            for (idx, item) in next_up.iter().enumerate() {
                content.push_str(&format!(
                    "{}. {}: {} ({}, {})\n",
                    idx + 1,
                    item.frontmatter.id,
                    item.frontmatter.title,
                    item.frontmatter.priority,
                    item.frontmatter.status
                ));
            }
            content.push('\n');
        }

        // Key metrics
        content.push_str("## Key Metrics\n");
        let total_open = backlog_items
            .iter()
            .filter(|i| {
                i.frontmatter.status != BacklogStatus::Done
                    && i.frontmatter.status != BacklogStatus::Cancelled
            })
            .count();
        let by_priority = |p: &Priority| {
            backlog_items
                .iter()
                .filter(|i| {
                    i.frontmatter.priority == *p
                        && i.frontmatter.status != BacklogStatus::Done
                        && i.frontmatter.status != BacklogStatus::Cancelled
                })
                .count()
        };
        let critical = by_priority(&Priority::Critical);
        let high = by_priority(&Priority::High);
        let medium = by_priority(&Priority::Medium);
        let low = by_priority(&Priority::Low);
        content.push_str(&format!(
            "- Backlog: {} items ({} critical, {} high, {} medium, {} low)\n",
            total_open, critical, high, medium, low
        ));
        content.push_str(&format!("- Last sync: {}\n", now));

        // Key Documentation section (from configured documentation_paths)
        let doc_files = self.list_documentation_files()?;
        if !doc_files.is_empty() {
            content.push_str("\n## Key Documentation\n");
            for (name, _) in &doc_files {
                content.push_str(&format!("- {}\n", name));
            }
        }

        let context_dir = self.root().join(".context");
        fs::create_dir_all(&context_dir)?;
        fs::write(context_dir.join("summary.md"), content)?;
        Ok(())
    }

    /// Generate .context/active-work.md
    pub fn generate_context_active_work(&self) -> Result<()> {
        let backlog_items = self.list_backlog_items(&QueryFilter::default())?;
        let plans = self.list_plans()?;
        let now = Local::now().format("%Y-%m-%d").to_string();

        let mut content = format!(
            "{}\n# Active Work\n<!-- Last updated: {} -->\n\n",
            GENERATED_HEADER, now
        );

        let in_progress: Vec<_> = backlog_items
            .iter()
            .filter(|i| i.frontmatter.status == BacklogStatus::InProgress)
            .collect();

        if in_progress.is_empty() {
            content.push_str("No items currently in progress.\n");
        } else {
            for item in &in_progress {
                let fm = &item.frontmatter;
                content.push_str(&format!("## {} — {}\n", fm.id, fm.title));
                content.push_str(&format!("- **Priority**: {}\n", fm.priority));
                content.push_str(&format!("- **Type**: {}\n", fm.item_type));
                content.push_str(&format!("- **Effort**: {}\n", fm.effort));
                if let Some(ref assignee) = fm.assignee {
                    content.push_str(&format!("- **Assignee**: @{}\n", assignee));
                }
                if let Some(ref epic) = fm.epic {
                    content.push_str(&format!("- **Epic**: [[{}]]\n", epic));
                }
                if let Some(ref plan) = fm.plan {
                    content.push_str(&format!("- **Plan**: [[{}]]\n", plan));
                }
                if !fm.depends_on.is_empty() {
                    let deps: Vec<String> =
                        fm.depends_on.iter().map(|d| format!("[[{}]]", d)).collect();
                    content.push_str(&format!("- **Depends on**: {}\n", deps.join(", ")));
                }
                if !fm.blocks.is_empty() {
                    let blocks: Vec<String> =
                        fm.blocks.iter().map(|b| format!("[[{}]]", b)).collect();
                    content.push_str(&format!("- **Blocks**: {}\n", blocks.join(", ")));
                }
                content.push('\n');
            }
        }

        // Active plans
        let active_plans: Vec<_> = plans
            .iter()
            .filter(|p| p.frontmatter.status == PlanStatus::InProgress)
            .collect();
        if !active_plans.is_empty() {
            content.push_str("## Active Plans\n\n");
            for plan in &active_plans {
                let implements_str = if plan.frontmatter.implements.is_empty() {
                    "—".to_string()
                } else {
                    plan.frontmatter
                        .implements
                        .iter()
                        .map(|id| format!("[[{}]]", id))
                        .collect::<Vec<_>>()
                        .join(", ")
                };
                content.push_str(&format!(
                    "- [[{}]] {} (implements: {})\n",
                    plan.frontmatter.id, plan.frontmatter.title, implements_str
                ));
            }
        }

        let context_dir = self.root().join(".context");
        fs::create_dir_all(&context_dir)?;
        fs::write(context_dir.join("active-work.md"), content)?;
        Ok(())
    }

    /// Generate .context/blocked-items.md
    pub fn generate_context_blocked(&self) -> Result<()> {
        let backlog_items = self.list_backlog_items(&QueryFilter::default())?;
        let now = Local::now().format("%Y-%m-%d").to_string();

        let mut content = format!(
            "{}\n# Blocked Items\n<!-- Last updated: {} -->\n\n",
            GENERATED_HEADER, now
        );

        let done_ids: HashSet<&str> = backlog_items
            .iter()
            .filter(|i| i.frontmatter.status == BacklogStatus::Done)
            .map(|i| i.frontmatter.id.as_str())
            .collect();

        let blocked = find_blocked_items(&backlog_items);

        if blocked.is_empty() {
            content.push_str("No blocked items.\n");
        } else {
            content.push_str(&format!("{} blocked items:\n\n", blocked.len()));
            for item in &blocked {
                let fm = &item.frontmatter;
                let blockers: Vec<String> = fm
                    .depends_on
                    .iter()
                    .filter(|dep| !done_ids.contains(dep.as_str()))
                    .map(|dep| format!("[[{}]]", dep))
                    .collect();
                content.push_str(&format!(
                    "- **[[{}]]** {} ({}) — blocked by {}\n",
                    fm.id,
                    fm.title,
                    fm.priority,
                    blockers.join(", ")
                ));
            }
        }

        let context_dir = self.root().join(".context");
        fs::create_dir_all(&context_dir)?;
        fs::write(context_dir.join("blocked-items.md"), content)?;
        Ok(())
    }

    /// Generate .context/metrics.md
    pub fn generate_context_metrics(&self) -> Result<()> {
        let backlog_items = self.list_backlog_items(&QueryFilter::default())?;
        let epics = self.list_epics()?;
        let plans = self.list_plans()?;
        let now = Local::now().format("%Y-%m-%d").to_string();

        let mut content = format!(
            "{}\n# Project Metrics\n<!-- Last updated: {} -->\n\n",
            GENERATED_HEADER, now
        );

        // Overall counts
        let total = backlog_items.len();
        let done = backlog_items
            .iter()
            .filter(|i| i.frontmatter.status == BacklogStatus::Done)
            .count();
        let cancelled = backlog_items
            .iter()
            .filter(|i| i.frontmatter.status == BacklogStatus::Cancelled)
            .count();
        let in_progress = backlog_items
            .iter()
            .filter(|i| i.frontmatter.status == BacklogStatus::InProgress)
            .count();
        let planned = backlog_items
            .iter()
            .filter(|i| i.frontmatter.status == BacklogStatus::Planned)
            .count();
        let backlog_count = backlog_items
            .iter()
            .filter(|i| i.frontmatter.status == BacklogStatus::Backlog)
            .count();
        let draft = backlog_items
            .iter()
            .filter(|i| i.frontmatter.status == BacklogStatus::Draft)
            .count();

        content.push_str("## Backlog Status Distribution\n");
        content.push_str(&format!("- Total: {}\n", total));
        content.push_str(&format!("- In Progress: {}\n", in_progress));
        content.push_str(&format!("- Planned: {}\n", planned));
        content.push_str(&format!("- Backlog: {}\n", backlog_count));
        content.push_str(&format!("- Draft: {}\n", draft));
        content.push_str(&format!("- Done: {}\n", done));
        content.push_str(&format!("- Cancelled: {}\n", cancelled));
        content.push('\n');

        // Priority distribution (open items only)
        content.push_str("## Priority Distribution (open items)\n");
        let priority_order = [
            ("Critical", Priority::Critical),
            ("High", Priority::High),
            ("Medium", Priority::Medium),
            ("Low", Priority::Low),
            ("Someday", Priority::Someday),
        ];
        for (label, priority) in &priority_order {
            let count = backlog_items
                .iter()
                .filter(|i| {
                    i.frontmatter.priority == *priority
                        && i.frontmatter.status != BacklogStatus::Done
                        && i.frontmatter.status != BacklogStatus::Cancelled
                })
                .count();
            content.push_str(&format!("- {}: {}\n", label, count));
        }
        content.push('\n');

        // Epic progress
        if !epics.is_empty() {
            content.push_str("## Epic Progress\n");
            for epic in &epics {
                let epic_items: Vec<_> = backlog_items
                    .iter()
                    .filter(|i| i.frontmatter.epic.as_deref() == Some(&epic.frontmatter.id))
                    .collect();
                let epic_total = epic_items.len();
                let epic_done = epic_items
                    .iter()
                    .filter(|i| i.frontmatter.status == BacklogStatus::Done)
                    .count();
                let pct = if epic_total > 0 {
                    (epic_done as f64 / epic_total as f64 * 100.0) as u32
                } else {
                    0
                };
                content.push_str(&format!(
                    "- [[{}]] {}: {}/{} ({}%) — {}\n",
                    epic.frontmatter.id,
                    epic.frontmatter.title,
                    epic_done,
                    epic_total,
                    pct,
                    epic.frontmatter.status
                ));
            }
            content.push('\n');
        }

        // Plans summary
        if !plans.is_empty() {
            content.push_str("## Plans Summary\n");
            let plans_active = plans
                .iter()
                .filter(|p| p.frontmatter.status != PlanStatus::Done)
                .count();
            let plans_done = plans
                .iter()
                .filter(|p| p.frontmatter.status == PlanStatus::Done)
                .count();
            content.push_str(&format!("- Active: {}\n", plans_active));
            content.push_str(&format!("- Completed: {}\n", plans_done));
        }

        let context_dir = self.root().join(".context");
        fs::create_dir_all(&context_dir)?;
        fs::write(context_dir.join("metrics.md"), content)?;
        Ok(())
    }

    /// Generate all .context/ files
    pub fn generate_all_context(&self) -> Result<()> {
        self.generate_context_summary()?;
        self.generate_context_active_work()?;
        self.generate_context_blocked()?;
        self.generate_context_metrics()?;
        Ok(())
    }

    /// Full sync: all INDEX.md + all .context/ files
    pub fn sync_all(&self) -> Result<()> {
        self.sync_all_indexes()?;
        self.generate_all_context()?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    fn setup_project() -> (TempDir, Project) {
        let tmp = TempDir::new().unwrap();
        let root = tmp.path().join(".markplane");
        let project = Project::init(root, "Test Project", "A test project").unwrap();
        (tmp, project)
    }

    #[test]
    fn test_generate_context_summary_empty() {
        let (_tmp, project) = setup_project();
        project.generate_context_summary().unwrap();
        let content =
            fs::read_to_string(project.root().join(".context/summary.md")).unwrap();
        assert!(content.contains(GENERATED_HEADER));
        assert!(content.contains("Project: Test Project"));
        assert!(content.contains("Key Metrics"));
        assert!(content.contains("Backlog: 0 items"));
    }

    #[test]
    fn test_generate_context_summary_with_items() {
        let (_tmp, project) = setup_project();
        project.create_epic("Phase 1", Priority::High).unwrap();
        project.update_status("EPIC-001", "active").unwrap();

        project
            .create_backlog_item(
                "In progress item",
                ItemType::Feature,
                Priority::High,
                Effort::Medium,
                Some("EPIC-001".to_string()),
                vec![],
            )
            .unwrap();
        project.update_status("BACK-001", "in-progress").unwrap();

        project
            .create_backlog_item(
                "Planned item",
                ItemType::Feature,
                Priority::Medium,
                Effort::Small,
                None,
                vec![],
            )
            .unwrap();
        project.update_status("BACK-002", "planned").unwrap();

        project.generate_context_summary().unwrap();
        let content =
            fs::read_to_string(project.root().join(".context/summary.md")).unwrap();
        assert!(content.contains("Active Epics"));
        assert!(content.contains("EPIC-001"));
        assert!(content.contains("In-Progress Work"));
        assert!(content.contains("BACK-001"));
        assert!(content.contains("Priority Queue"));
        assert!(content.contains("BACK-002"));
    }

    #[test]
    fn test_generate_context_summary_blocked() {
        let (_tmp, project) = setup_project();
        project
            .create_backlog_item(
                "Blocker",
                ItemType::Feature,
                Priority::High,
                Effort::Small,
                None,
                vec![],
            )
            .unwrap();
        project.update_status("BACK-001", "in-progress").unwrap();

        // Create item that depends on BACK-001 (not done)
        project
            .create_backlog_item(
                "Blocked item",
                ItemType::Feature,
                Priority::High,
                Effort::Medium,
                None,
                vec![],
            )
            .unwrap();
        // Manually set depends_on by reading/writing the item
        let mut doc: MarkplaneDocument<BacklogItem> = project.read_item("BACK-002").unwrap();
        doc.frontmatter.depends_on = vec!["BACK-001".to_string()];
        project.write_item("BACK-002", &doc).unwrap();

        project.generate_context_summary().unwrap();
        let content =
            fs::read_to_string(project.root().join(".context/summary.md")).unwrap();
        assert!(content.contains("Blocked Items"));
        assert!(content.contains("BACK-002"));
        assert!(content.contains("blocked by BACK-001"));
    }

    #[test]
    fn test_generate_context_active_work_empty() {
        let (_tmp, project) = setup_project();
        project.generate_context_active_work().unwrap();
        let content =
            fs::read_to_string(project.root().join(".context/active-work.md")).unwrap();
        assert!(content.contains("No items currently in progress"));
    }

    #[test]
    fn test_generate_context_active_work_with_items() {
        let (_tmp, project) = setup_project();
        project
            .create_backlog_item(
                "Active item",
                ItemType::Bug,
                Priority::Critical,
                Effort::Small,
                None,
                vec![],
            )
            .unwrap();
        project.update_status("BACK-001", "in-progress").unwrap();

        project.generate_context_active_work().unwrap();
        let content =
            fs::read_to_string(project.root().join(".context/active-work.md")).unwrap();
        assert!(content.contains("BACK-001"));
        assert!(content.contains("Active item"));
        assert!(content.contains("critical"));
    }

    #[test]
    fn test_generate_context_blocked_empty() {
        let (_tmp, project) = setup_project();
        project.generate_context_blocked().unwrap();
        let content =
            fs::read_to_string(project.root().join(".context/blocked-items.md")).unwrap();
        assert!(content.contains("No blocked items"));
    }

    #[test]
    fn test_generate_context_blocked_with_items() {
        let (_tmp, project) = setup_project();
        project
            .create_backlog_item(
                "Blocker",
                ItemType::Feature,
                Priority::High,
                Effort::Small,
                None,
                vec![],
            )
            .unwrap();
        project
            .create_backlog_item(
                "Blocked",
                ItemType::Feature,
                Priority::High,
                Effort::Medium,
                None,
                vec![],
            )
            .unwrap();
        let mut doc: MarkplaneDocument<BacklogItem> = project.read_item("BACK-002").unwrap();
        doc.frontmatter.depends_on = vec!["BACK-001".to_string()];
        project.write_item("BACK-002", &doc).unwrap();

        project.generate_context_blocked().unwrap();
        let content =
            fs::read_to_string(project.root().join(".context/blocked-items.md")).unwrap();
        assert!(content.contains("1 blocked items"));
        assert!(content.contains("BACK-002"));
        assert!(content.contains("[[BACK-001]]"));
    }

    #[test]
    fn test_generate_context_metrics() {
        let (_tmp, project) = setup_project();
        project.create_epic("Phase 1", Priority::High).unwrap();
        project
            .create_backlog_item(
                "Item 1",
                ItemType::Feature,
                Priority::High,
                Effort::Medium,
                Some("EPIC-001".to_string()),
                vec![],
            )
            .unwrap();
        project
            .create_backlog_item(
                "Item 2",
                ItemType::Bug,
                Priority::Critical,
                Effort::Small,
                None,
                vec![],
            )
            .unwrap();

        project.generate_context_metrics().unwrap();
        let content =
            fs::read_to_string(project.root().join(".context/metrics.md")).unwrap();
        assert!(content.contains("Project Metrics"));
        assert!(content.contains("Total: 2"));
        assert!(content.contains("Draft: 2"));
        assert!(content.contains("Critical: 1"));
        assert!(content.contains("High: 1"));
        assert!(content.contains("Epic Progress"));
        assert!(content.contains("EPIC-001"));
    }

    #[test]
    fn test_generate_all_context() {
        let (_tmp, project) = setup_project();
        project.generate_all_context().unwrap();

        assert!(project.root().join(".context/summary.md").is_file());
        assert!(project.root().join(".context/active-work.md").is_file());
        assert!(project.root().join(".context/blocked-items.md").is_file());
        assert!(project.root().join(".context/metrics.md").is_file());
    }

    #[test]
    fn test_sync_all() {
        let (_tmp, project) = setup_project();
        project.create_epic("Phase 1", Priority::High).unwrap();
        project
            .create_backlog_item(
                "Item 1",
                ItemType::Feature,
                Priority::High,
                Effort::Medium,
                Some("EPIC-001".to_string()),
                vec![],
            )
            .unwrap();

        project.sync_all().unwrap();

        // Indexes should be generated
        let root_index = fs::read_to_string(project.root().join("INDEX.md")).unwrap();
        assert!(root_index.contains(GENERATED_HEADER));

        // Context files should be generated
        let summary =
            fs::read_to_string(project.root().join(".context/summary.md")).unwrap();
        assert!(summary.contains("Test Project"));

        let metrics =
            fs::read_to_string(project.root().join(".context/metrics.md")).unwrap();
        assert!(metrics.contains("Total: 1"));
    }

    #[test]
    fn test_generate_context_summary_with_documentation() {
        let (tmp, project) = setup_project();
        let docs_dir = tmp.path().join("docs");
        fs::create_dir_all(&docs_dir).unwrap();
        fs::write(docs_dir.join("architecture.md"), "# Architecture").unwrap();

        let mut config = project.load_config().unwrap();
        config.documentation_paths = vec!["docs".to_string()];
        project.save_config(&config).unwrap();

        project.generate_context_summary().unwrap();
        let content =
            fs::read_to_string(project.root().join(".context/summary.md")).unwrap();
        assert!(content.contains("## Key Documentation"));
        assert!(content.contains("- architecture"));
    }

    #[test]
    fn test_generate_context_summary_no_documentation_when_empty() {
        let (_tmp, project) = setup_project();
        project.generate_context_summary().unwrap();
        let content =
            fs::read_to_string(project.root().join(".context/summary.md")).unwrap();
        assert!(!content.contains("Key Documentation"));
    }
}
