use std::fs;

use chrono::Local;

use crate::error::Result;
use crate::models::*;
use crate::project::Project;
use crate::query::QueryFilter;

const GENERATED_HEADER: &str = "<!-- Generated by markplane sync -->";

impl Project {
    /// Regenerate the root INDEX.md.
    pub fn generate_root_index(&self) -> Result<()> {
        let config = self.load_config()?;
        let now = Local::now().format("%Y-%m-%d").to_string();

        let backlog_items = self.list_backlog_items(&QueryFilter::default())?;
        let epics = self.list_epics()?;
        let plans = self.list_plans()?;
        let notes = self.list_notes()?;

        let active_epics = epics
            .iter()
            .filter(|e| e.frontmatter.status != EpicStatus::Done)
            .count();
        let open_backlog = backlog_items
            .iter()
            .filter(|b| {
                b.frontmatter.status != BacklogStatus::Done
                    && b.frontmatter.status != BacklogStatus::Cancelled
            })
            .count();
        let active_plans = plans
            .iter()
            .filter(|p| p.frontmatter.status != PlanStatus::Done)
            .count();
        let active_notes = notes
            .iter()
            .filter(|n| n.frontmatter.status != NoteStatus::Archived)
            .count();

        // Build counter string from config
        let counter_parts: Vec<String> = ["EPIC", "BACK", "PLAN", "NOTE"]
            .iter()
            .map(|prefix| {
                let count = config.counters.get(*prefix).copied().unwrap_or(0);
                format!("{}-{:03}", prefix, count)
            })
            .collect();
        let counters_str = counter_parts.join(", ");

        let content = format!(
            "{}\n# Markplane Project Index\n\n\
             ## Quick Navigation\n\n\
             | Module | Path | Purpose | Active Items |\n\
             |--------|------|---------|-------------|\n\
             | Roadmap | [roadmap/](roadmap/INDEX.md) | Strategic phases & epics | {} active epics |\n\
             | Backlog | [backlog/](backlog/INDEX.md) | All work items | {} open items |\n\
             | Plans | [plans/](plans/INDEX.md) | Implementation details | {} active plans |\n\
             | Notes | [notes/](notes/INDEX.md) | Research & ideas | {} active notes |\n\
             | Knowledge Base | [kb/](kb/INDEX.md) | Architecture & guides | — |\n\
             | AI Context | [.context/](.context/summary.md) | Generated summaries | Auto-updated |\n\n\
             ## System Info\n\
             - ID counter: {}\n\
             - Last sync: {}\n\
             - Config: [config.yaml](config.yaml)\n",
            GENERATED_HEADER,
            active_epics,
            open_backlog,
            active_plans,
            active_notes,
            counters_str,
            now,
        );

        fs::write(self.root().join("INDEX.md"), content)?;
        Ok(())
    }

    /// Regenerate backlog/INDEX.md grouped by status, priority, and epic.
    pub fn generate_backlog_index(&self) -> Result<()> {
        let items = self.list_backlog_items(&QueryFilter::default())?;
        let epics = self.list_epics()?;

        let mut content = format!("{}\n# Backlog Index\n\n## By Status\n", GENERATED_HEADER);

        // Group by status in display order
        let status_order = [
            ("In Progress", BacklogStatus::InProgress),
            ("Planned", BacklogStatus::Planned),
            ("Backlog", BacklogStatus::Backlog),
            ("Draft", BacklogStatus::Draft),
        ];

        for (label, status) in &status_order {
            let matching: Vec<_> = items
                .iter()
                .filter(|i| i.frontmatter.status == *status)
                .collect();
            if matching.is_empty() {
                continue;
            }
            content.push_str(&format!("\n### {} ({})\n", label, matching.len()));
            for item in &matching {
                let fm = &item.frontmatter;
                let assignee_str = fm
                    .assignee
                    .as_ref()
                    .map(|a| format!(", @{}", a))
                    .unwrap_or_default();
                let plan_str = fm
                    .plan
                    .as_ref()
                    .map(|p| format!(", {}", p))
                    .unwrap_or_default();
                content.push_str(&format!(
                    "- [[{}]] {} ({}{}{})\n",
                    fm.id, fm.title, fm.priority, plan_str, assignee_str
                ));
            }
        }

        // By Priority counts
        content.push_str("\n## By Priority\n");
        let priority_order = [
            ("Critical", Priority::Critical),
            ("High", Priority::High),
            ("Medium", Priority::Medium),
            ("Low", Priority::Low),
            ("Someday", Priority::Someday),
        ];
        for (label, priority) in &priority_order {
            let count = items
                .iter()
                .filter(|i| {
                    i.frontmatter.priority == *priority
                        && i.frontmatter.status != BacklogStatus::Done
                        && i.frontmatter.status != BacklogStatus::Cancelled
                })
                .count();
            if count > 0 {
                content.push_str(&format!("- {}: {} items\n", label, count));
            }
        }

        // By Epic
        content.push_str("\n## By Epic\n");
        for epic_doc in &epics {
            let epic_id = &epic_doc.frontmatter.id;
            let epic_items: Vec<_> = items
                .iter()
                .filter(|i| i.frontmatter.epic.as_deref() == Some(epic_id))
                .collect();
            if epic_items.is_empty() {
                continue;
            }
            let done_count = epic_items
                .iter()
                .filter(|i| i.frontmatter.status == BacklogStatus::Done)
                .count();
            let in_progress_count = epic_items
                .iter()
                .filter(|i| i.frontmatter.status == BacklogStatus::InProgress)
                .count();
            let planned_count = epic_items
                .iter()
                .filter(|i| i.frontmatter.status == BacklogStatus::Planned)
                .count();
            let backlog_count = epic_items.len() - done_count - in_progress_count - planned_count;
            content.push_str(&format!(
                "- [[{}]]: {} items ({} done, {} in-progress, {} planned, {} other)\n",
                epic_id,
                epic_items.len(),
                done_count,
                in_progress_count,
                planned_count,
                backlog_count
            ));
        }

        // Unassigned to any epic
        let orphan_count = items
            .iter()
            .filter(|i| i.frontmatter.epic.is_none())
            .count();
        if orphan_count > 0 {
            content.push_str(&format!("- (no epic): {} items\n", orphan_count));
        }

        fs::write(self.root().join("backlog/INDEX.md"), content)?;
        Ok(())
    }

    /// Regenerate roadmap/INDEX.md with epic list and progress.
    pub fn generate_roadmap_index(&self) -> Result<()> {
        let epics = self.list_epics()?;
        let backlog_items = self.list_backlog_items(&QueryFilter::default())?;

        let mut content = format!("{}\n# Roadmap Index\n\n", GENERATED_HEADER);

        // Active epics
        let active_epics: Vec<_> = epics
            .iter()
            .filter(|e| e.frontmatter.status == EpicStatus::Active)
            .collect();
        if !active_epics.is_empty() {
            content.push_str("## Active Epics\n\n");
            content.push_str("| Epic | Status | Priority | Progress |\n");
            content.push_str("|------|--------|----------|----------|\n");
            for epic in &active_epics {
                let (done, total) = epic_progress(&epic.frontmatter.id, &backlog_items);
                let pct = if total > 0 {
                    (done as f64 / total as f64 * 100.0) as u32
                } else {
                    0
                };
                content.push_str(&format!(
                    "| [[{}]] {} | {} | {} | {}/{} ({}%) |\n",
                    epic.frontmatter.id,
                    epic.frontmatter.title,
                    epic.frontmatter.status,
                    epic.frontmatter.priority,
                    done,
                    total,
                    pct
                ));
            }
            content.push('\n');
        }

        // Planned epics
        let planned_epics: Vec<_> = epics
            .iter()
            .filter(|e| e.frontmatter.status == EpicStatus::Planned)
            .collect();
        if !planned_epics.is_empty() {
            content.push_str("## Planned Epics\n\n");
            for epic in &planned_epics {
                content.push_str(&format!(
                    "- [[{}]] {} ({})\n",
                    epic.frontmatter.id, epic.frontmatter.title, epic.frontmatter.priority
                ));
            }
            content.push('\n');
        }

        // Paused epics
        let paused_epics: Vec<_> = epics
            .iter()
            .filter(|e| e.frontmatter.status == EpicStatus::Paused)
            .collect();
        if !paused_epics.is_empty() {
            content.push_str("## Paused Epics\n\n");
            for epic in &paused_epics {
                content.push_str(&format!(
                    "- [[{}]] {} ({})\n",
                    epic.frontmatter.id, epic.frontmatter.title, epic.frontmatter.priority
                ));
            }
            content.push('\n');
        }

        // Done epics
        let done_epics: Vec<_> = epics
            .iter()
            .filter(|e| e.frontmatter.status == EpicStatus::Done)
            .collect();
        if !done_epics.is_empty() {
            content.push_str("## Completed Epics\n\n");
            for epic in &done_epics {
                let (done, total) = epic_progress(&epic.frontmatter.id, &backlog_items);
                content.push_str(&format!(
                    "- [[{}]] {} ({}/{})\n",
                    epic.frontmatter.id, epic.frontmatter.title, done, total
                ));
            }
            content.push('\n');
        }

        fs::write(self.root().join("roadmap/INDEX.md"), content)?;
        Ok(())
    }

    /// Regenerate plans/INDEX.md with active/completed plans.
    pub fn generate_plans_index(&self) -> Result<()> {
        let plans = self.list_plans()?;

        let mut content = format!("{}\n# Plans Index\n\n", GENERATED_HEADER);

        // Active plans (draft, approved, in-progress)
        let active_plans: Vec<_> = plans
            .iter()
            .filter(|p| p.frontmatter.status != PlanStatus::Done)
            .collect();
        if !active_plans.is_empty() {
            content.push_str("## Active Plans\n\n");
            content.push_str("| Plan | Status | Implements |\n");
            content.push_str("|------|--------|------------|\n");
            for plan in &active_plans {
                let implements_str = if plan.frontmatter.implements.is_empty() {
                    "—".to_string()
                } else {
                    plan.frontmatter
                        .implements
                        .iter()
                        .map(|id| format!("[[{}]]", id))
                        .collect::<Vec<_>>()
                        .join(", ")
                };
                content.push_str(&format!(
                    "| [[{}]] {} | {} | {} |\n",
                    plan.frontmatter.id,
                    plan.frontmatter.title,
                    plan.frontmatter.status,
                    implements_str
                ));
            }
            content.push('\n');
        }

        // Done plans
        let done_plans: Vec<_> = plans
            .iter()
            .filter(|p| p.frontmatter.status == PlanStatus::Done)
            .collect();
        if !done_plans.is_empty() {
            content.push_str("## Completed Plans\n\n");
            for plan in &done_plans {
                content.push_str(&format!(
                    "- [[{}]] {}\n",
                    plan.frontmatter.id, plan.frontmatter.title
                ));
            }
            content.push('\n');
        }

        fs::write(self.root().join("plans/INDEX.md"), content)?;
        Ok(())
    }

    /// Regenerate notes/INDEX.md with active notes.
    pub fn generate_notes_index(&self) -> Result<()> {
        let notes = self.list_notes()?;

        let mut content = format!("{}\n# Notes Index\n\n", GENERATED_HEADER);

        // Active/draft notes
        let active_notes: Vec<_> = notes
            .iter()
            .filter(|n| n.frontmatter.status != NoteStatus::Archived)
            .collect();
        if !active_notes.is_empty() {
            content.push_str("## Active Notes\n\n");
            content.push_str("| Note | Type | Status | Tags |\n");
            content.push_str("|------|------|--------|------|\n");
            for note in &active_notes {
                let tags_str = if note.frontmatter.tags.is_empty() {
                    "—".to_string()
                } else {
                    note.frontmatter.tags.join(", ")
                };
                content.push_str(&format!(
                    "| [[{}]] {} | {} | {} | {} |\n",
                    note.frontmatter.id,
                    note.frontmatter.title,
                    note.frontmatter.note_type,
                    note.frontmatter.status,
                    tags_str
                ));
            }
            content.push('\n');
        }

        // Archived notes
        let archived_notes: Vec<_> = notes
            .iter()
            .filter(|n| n.frontmatter.status == NoteStatus::Archived)
            .collect();
        if !archived_notes.is_empty() {
            content.push_str("## Archived Notes\n\n");
            for note in &archived_notes {
                content.push_str(&format!(
                    "- [[{}]] {} ({})\n",
                    note.frontmatter.id, note.frontmatter.title, note.frontmatter.note_type
                ));
            }
            content.push('\n');
        }

        // Special files
        content.push_str("## Special Files\n");
        content.push_str("- [ideas.md](ideas.md) — Quick capture\n");
        content.push_str("- [decisions.md](decisions.md) — Decision log\n");

        fs::write(self.root().join("notes/INDEX.md"), content)?;
        Ok(())
    }

    /// Regenerate all INDEX.md files.
    pub fn sync_all_indexes(&self) -> Result<()> {
        self.generate_root_index()?;
        self.generate_backlog_index()?;
        self.generate_roadmap_index()?;
        self.generate_plans_index()?;
        self.generate_notes_index()?;
        Ok(())
    }
}

/// Count (done, total) backlog items for a given epic.
fn epic_progress(epic_id: &str, items: &[MarkplaneDocument<BacklogItem>]) -> (usize, usize) {
    let epic_items: Vec<_> = items
        .iter()
        .filter(|i| i.frontmatter.epic.as_deref() == Some(epic_id))
        .collect();
    let total = epic_items.len();
    let done = epic_items
        .iter()
        .filter(|i| i.frontmatter.status == BacklogStatus::Done)
        .count();
    (done, total)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn setup_project() -> (TempDir, Project) {
        let tmp = TempDir::new().unwrap();
        let root = tmp.path().join(".markplane");
        let project = Project::init(root, "Test Project", "A test project").unwrap();
        (tmp, project)
    }

    #[test]
    fn test_generate_root_index_empty() {
        let (_tmp, project) = setup_project();
        project.generate_root_index().unwrap();
        let content = fs::read_to_string(project.root().join("INDEX.md")).unwrap();
        assert!(content.contains(GENERATED_HEADER));
        assert!(content.contains("Markplane Project Index"));
        assert!(content.contains("0 active epics"));
        assert!(content.contains("0 open items"));
        assert!(content.contains("Last sync:"));
    }

    #[test]
    fn test_generate_root_index_with_items() {
        let (_tmp, project) = setup_project();
        project.create_epic("Phase 1", Priority::High).unwrap();
        project
            .create_backlog_item(
                "Item 1",
                ItemType::Feature,
                Priority::High,
                Effort::Medium,
                None,
                vec![],
            )
            .unwrap();
        project.generate_root_index().unwrap();

        let content = fs::read_to_string(project.root().join("INDEX.md")).unwrap();
        assert!(content.contains("1 active epics"));
        assert!(content.contains("1 open items"));
        assert!(content.contains("EPIC-001"));
        assert!(content.contains("BACK-001"));
    }

    #[test]
    fn test_generate_backlog_index_empty() {
        let (_tmp, project) = setup_project();
        project.generate_backlog_index().unwrap();
        let content = fs::read_to_string(project.root().join("backlog/INDEX.md")).unwrap();
        assert!(content.contains(GENERATED_HEADER));
        assert!(content.contains("Backlog Index"));
    }

    #[test]
    fn test_generate_backlog_index_groups_by_status() {
        let (_tmp, project) = setup_project();
        project
            .create_backlog_item(
                "Draft item",
                ItemType::Feature,
                Priority::Medium,
                Effort::Small,
                None,
                vec![],
            )
            .unwrap();
        project
            .create_backlog_item(
                "Progress item",
                ItemType::Bug,
                Priority::High,
                Effort::Medium,
                None,
                vec![],
            )
            .unwrap();
        project.update_status("BACK-002", "in-progress").unwrap();

        project.generate_backlog_index().unwrap();
        let content = fs::read_to_string(project.root().join("backlog/INDEX.md")).unwrap();
        assert!(content.contains("### In Progress (1)"));
        assert!(content.contains("### Draft (1)"));
        assert!(content.contains("[[BACK-002]]"));
        assert!(content.contains("[[BACK-001]]"));
    }

    #[test]
    fn test_generate_backlog_index_priority_counts() {
        let (_tmp, project) = setup_project();
        project
            .create_backlog_item(
                "High 1",
                ItemType::Feature,
                Priority::High,
                Effort::Small,
                None,
                vec![],
            )
            .unwrap();
        project
            .create_backlog_item(
                "High 2",
                ItemType::Feature,
                Priority::High,
                Effort::Small,
                None,
                vec![],
            )
            .unwrap();
        project
            .create_backlog_item(
                "Medium 1",
                ItemType::Feature,
                Priority::Medium,
                Effort::Small,
                None,
                vec![],
            )
            .unwrap();

        project.generate_backlog_index().unwrap();
        let content = fs::read_to_string(project.root().join("backlog/INDEX.md")).unwrap();
        assert!(content.contains("High: 2 items"));
        assert!(content.contains("Medium: 1 items"));
    }

    #[test]
    fn test_generate_backlog_index_by_epic() {
        let (_tmp, project) = setup_project();
        project.create_epic("Phase 1", Priority::High).unwrap();
        project
            .create_backlog_item(
                "Item in epic",
                ItemType::Feature,
                Priority::High,
                Effort::Medium,
                Some("EPIC-001".to_string()),
                vec![],
            )
            .unwrap();
        project
            .create_backlog_item(
                "Orphan item",
                ItemType::Feature,
                Priority::Medium,
                Effort::Small,
                None,
                vec![],
            )
            .unwrap();

        project.generate_backlog_index().unwrap();
        let content = fs::read_to_string(project.root().join("backlog/INDEX.md")).unwrap();
        assert!(content.contains("[[EPIC-001]]: 1 items"));
        assert!(content.contains("(no epic): 1 items"));
    }

    #[test]
    fn test_generate_roadmap_index() {
        let (_tmp, project) = setup_project();
        project.create_epic("Active Epic", Priority::High).unwrap();
        project.update_status("EPIC-001", "active").unwrap();
        project.create_epic("Planned Epic", Priority::Medium).unwrap();

        // Add a backlog item linked to the active epic
        project
            .create_backlog_item(
                "Item 1",
                ItemType::Feature,
                Priority::High,
                Effort::Medium,
                Some("EPIC-001".to_string()),
                vec![],
            )
            .unwrap();

        project.generate_roadmap_index().unwrap();
        let content = fs::read_to_string(project.root().join("roadmap/INDEX.md")).unwrap();
        assert!(content.contains(GENERATED_HEADER));
        assert!(content.contains("Active Epics"));
        assert!(content.contains("[[EPIC-001]]"));
        assert!(content.contains("0/1 (0%)"));
        assert!(content.contains("Planned Epics"));
        assert!(content.contains("[[EPIC-002]]"));
    }

    #[test]
    fn test_generate_plans_index() {
        let (_tmp, project) = setup_project();
        project
            .create_plan("Active Plan", vec!["BACK-001".to_string()], None)
            .unwrap();
        project.create_plan("Done Plan", vec![], None).unwrap();
        project.update_status("PLAN-002", "done").unwrap();

        project.generate_plans_index().unwrap();
        let content = fs::read_to_string(project.root().join("plans/INDEX.md")).unwrap();
        assert!(content.contains("Active Plans"));
        assert!(content.contains("[[PLAN-001]]"));
        assert!(content.contains("[[BACK-001]]"));
        assert!(content.contains("Completed Plans"));
        assert!(content.contains("[[PLAN-002]]"));
    }

    #[test]
    fn test_generate_notes_index() {
        let (_tmp, project) = setup_project();
        project
            .create_note("Research A", NoteType::Research, vec!["cache".to_string()])
            .unwrap();
        project
            .create_note("Analysis B", NoteType::Analysis, vec![])
            .unwrap();

        project.generate_notes_index().unwrap();
        let content = fs::read_to_string(project.root().join("notes/INDEX.md")).unwrap();
        assert!(content.contains(GENERATED_HEADER));
        assert!(content.contains("Active Notes"));
        assert!(content.contains("[[NOTE-001]]"));
        assert!(content.contains("cache"));
        assert!(content.contains("Special Files"));
        assert!(content.contains("ideas.md"));
    }

    #[test]
    fn test_sync_all_indexes() {
        let (_tmp, project) = setup_project();
        project.create_epic("Phase 1", Priority::High).unwrap();
        project
            .create_backlog_item(
                "Item 1",
                ItemType::Feature,
                Priority::High,
                Effort::Medium,
                Some("EPIC-001".to_string()),
                vec![],
            )
            .unwrap();

        project.sync_all_indexes().unwrap();

        // All index files should exist and be generated
        assert!(fs::read_to_string(project.root().join("INDEX.md"))
            .unwrap()
            .contains(GENERATED_HEADER));
        assert!(fs::read_to_string(project.root().join("backlog/INDEX.md"))
            .unwrap()
            .contains(GENERATED_HEADER));
        assert!(fs::read_to_string(project.root().join("roadmap/INDEX.md"))
            .unwrap()
            .contains(GENERATED_HEADER));
        assert!(fs::read_to_string(project.root().join("plans/INDEX.md"))
            .unwrap()
            .contains(GENERATED_HEADER));
        assert!(fs::read_to_string(project.root().join("notes/INDEX.md"))
            .unwrap()
            .contains(GENERATED_HEADER));
    }
}
