use std::collections::HashSet;
use std::fs;

use chrono::Local;

use crate::error::Result;
use crate::models::*;
use crate::project::{Project, find_blocked_items};
use crate::query::QueryFilter;

const GENERATED_HEADER: &str = "<!-- Generated by markplane sync -->";

impl Project {
    /// Regenerate the root INDEX.md.
    pub fn generate_root_index(&self) -> Result<()> {
        let now = Local::now().format("%Y-%m-%d").to_string();

        let tasks = self.list_tasks(&QueryFilter::default())?;
        let epics = self.list_epics()?;
        let plans = self.list_plans()?;
        let notes = self.list_notes()?;

        let active_epics = epics
            .iter()
            .filter(|e| e.frontmatter.status != EpicStatus::Done)
            .count();
        let open_backlog = tasks
            .iter()
            .filter(|b| {
                b.frontmatter.status != TaskStatus::Done
                    && b.frontmatter.status != TaskStatus::Cancelled
            })
            .count();
        let active_plans = plans
            .iter()
            .filter(|p| p.frontmatter.status != PlanStatus::Done)
            .count();
        let active_notes = notes
            .iter()
            .filter(|n| n.frontmatter.status != NoteStatus::Archived)
            .count();

        let mut content = format!(
            "{}\n# Markplane Project Index\n\n\
             ## Quick Navigation\n\n\
             | Module | Path | Purpose | Active Items |\n\
             |--------|------|---------|-------------|\n\
             | Roadmap | [roadmap/](roadmap/INDEX.md) | Strategic phases & epics | {} active epics |\n\
             | Backlog | [backlog/](backlog/INDEX.md) | All work items | {} open items |\n\
             | Plans | [plans/](plans/INDEX.md) | Implementation details | {} active plans |\n\
             | Notes | [notes/](notes/INDEX.md) | Research & ideas | {} active notes |\n\
             | AI Context | [.context/](.context/summary.md) | Generated summaries | Auto-updated |\n\n\
             ## System Info\n\
             - Last sync: {}\n\
             - Config: [config.yaml](config.yaml)\n",
            GENERATED_HEADER,
            active_epics,
            open_backlog,
            active_plans,
            active_notes,
            now,
        );

        // Project Documentation section (from configured documentation_paths)
        let doc_files = self.list_documentation_files()?;
        if !doc_files.is_empty() {
            content.push_str("\n## Project Documentation\n\n");
            content.push_str("| Document | Path |\n");
            content.push_str("|----------|------|\n");
            for (name, rel_path) in &doc_files {
                content.push_str(&format!("| {} | [{}]({}) |\n", name, rel_path, rel_path));
            }
        }

        fs::write(self.root().join("INDEX.md"), content)?;
        Ok(())
    }

    /// Regenerate backlog/INDEX.md as a prioritized kanban view.
    pub fn generate_backlog_index(&self) -> Result<()> {
        let config = self.load_config()?;
        let today = Local::now().date_naive();
        let recent_cutoff = today - chrono::Duration::days(config.context.recent_days as i64);

        let items = self.list_tasks(&QueryFilter::default())?;

        let mut content = format!("{}\n# Backlog Index\n\n", GENERATED_HEADER);

        // Build done_ids set for blocked-item dependency resolution
        let done_ids: HashSet<&str> = items
            .iter()
            .filter(|i| i.frontmatter.status == TaskStatus::Done)
            .map(|i| i.frontmatter.id.as_str())
            .collect();

        // Compute blocked items (items with unresolved depends_on)
        let blocked = find_blocked_items(&items);
        let blocked_ids: HashSet<&str> = blocked
            .iter()
            .map(|i| i.frontmatter.id.as_str())
            .collect();

        // --- In Progress ---
        let in_progress: Vec<_> = items
            .iter()
            .filter(|i| i.frontmatter.status == TaskStatus::InProgress)
            .collect();
        content.push_str(&format!("## In Progress ({})\n\n", in_progress.len()));
        if !in_progress.is_empty() {
            content.push_str("| ID | Title | Epic | Priority | Effort |\n");
            content.push_str("|----|-------|------|----------|--------|\n");
            for item in &in_progress {
                let fm = &item.frontmatter;
                let epic_str = epic_cell(&fm.epic);
                content.push_str(&format!(
                    "| {} | {} | {} | {} | {} |\n",
                    item_link(&fm.id), fm.title, epic_str, fm.priority, fm.effort
                ));
            }
            content.push('\n');
        }

        // --- Blocked ---
        content.push_str(&format!("## Blocked ({})\n\n", blocked.len()));
        if !blocked.is_empty() {
            content.push_str("| ID | Title | Blocked By | Epic | Priority |\n");
            content.push_str("|----|-------|------------|------|----------|\n");
            for item in &blocked {
                let fm = &item.frontmatter;
                let unresolved: Vec<String> = fm
                    .depends_on
                    .iter()
                    .filter(|dep| !done_ids.contains(dep.as_str()))
                    .map(|dep| cross_link(dep))
                    .collect();
                let epic_str = epic_cell(&fm.epic);
                content.push_str(&format!(
                    "| {} | {} | {} | {} | {} |\n",
                    item_link(&fm.id), fm.title, unresolved.join(", "), epic_str, fm.priority
                ));
            }
            content.push('\n');
        }

        // --- Planned (ready to start, excluding blocked) ---
        let planned: Vec<_> = items
            .iter()
            .filter(|i| {
                i.frontmatter.status == TaskStatus::Planned
                    && !blocked_ids.contains(i.frontmatter.id.as_str())
            })
            .collect();
        content.push_str(&format!("## Planned ({})\n\n", planned.len()));
        if !planned.is_empty() {
            content.push_str("| ID | Title | Epic | Priority | Effort |\n");
            content.push_str("|----|-------|------|----------|--------|\n");
            for item in &planned {
                let fm = &item.frontmatter;
                let epic_str = epic_cell(&fm.epic);
                content.push_str(&format!(
                    "| {} | {} | {} | {} | {} |\n",
                    item_link(&fm.id), fm.title, epic_str, fm.priority, fm.effort
                ));
            }
            content.push('\n');
        }

        // --- Backlog (accepted but not yet scoped, excluding blocked) ---
        let backlog: Vec<_> = items
            .iter()
            .filter(|i| {
                i.frontmatter.status == TaskStatus::Backlog
                    && !blocked_ids.contains(i.frontmatter.id.as_str())
            })
            .collect();
        content.push_str(&format!("## Backlog ({})\n\n", backlog.len()));
        if !backlog.is_empty() {
            content.push_str("| ID | Title | Epic | Priority | Effort |\n");
            content.push_str("|----|-------|------|----------|--------|\n");
            for item in &backlog {
                let fm = &item.frontmatter;
                let epic_str = epic_cell(&fm.epic);
                content.push_str(&format!(
                    "| {} | {} | {} | {} | {} |\n",
                    item_link(&fm.id), fm.title, epic_str, fm.priority, fm.effort
                ));
            }
            content.push('\n');
        }

        // --- Drafts (excluding blocked) ---
        let drafts: Vec<_> = items
            .iter()
            .filter(|i| {
                i.frontmatter.status == TaskStatus::Draft
                    && !blocked_ids.contains(i.frontmatter.id.as_str())
            })
            .collect();
        content.push_str(&format!("## Drafts ({})\n\n", drafts.len()));
        if !drafts.is_empty() {
            content.push_str("| ID | Title | Epic | Priority | Effort |\n");
            content.push_str("|----|-------|------|----------|--------|\n");
            for item in &drafts {
                let fm = &item.frontmatter;
                let epic_str = epic_cell(&fm.epic);
                content.push_str(&format!(
                    "| {} | {} | {} | {} | {} |\n",
                    item_link(&fm.id), fm.title, epic_str, fm.priority, fm.effort
                ));
            }
            content.push('\n');
        }

        // --- Recently Done (completed within recent_days) ---
        let recently_done: Vec<_> = items
            .iter()
            .filter(|i| {
                i.frontmatter.status == TaskStatus::Done
                    && i.frontmatter.updated >= recent_cutoff
            })
            .collect();
        if !recently_done.is_empty() {
            content.push_str(&format!(
                "## Recently Done ({})\n\n",
                recently_done.len()
            ));
            content.push_str("| ID | Title | Epic | Completed |\n");
            content.push_str("|----|-------|------|-----------|\n");
            for item in &recently_done {
                let fm = &item.frontmatter;
                let epic_str = epic_cell(&fm.epic);
                content.push_str(&format!(
                    "| {} | {} | {} | {} |\n",
                    item_link(&fm.id), fm.title, epic_str, fm.updated
                ));
            }
            content.push('\n');
        }

        fs::write(self.root().join("backlog/INDEX.md"), content)?;
        Ok(())
    }

    /// Regenerate roadmap/INDEX.md with epics and nested task tables.
    pub fn generate_roadmap_index(&self) -> Result<()> {
        let epics = self.list_epics()?;
        let tasks = self.list_tasks(&QueryFilter::default())?;

        let mut content = format!("{}\n# Roadmap Index\n\n", GENERATED_HEADER);

        let status_groups: &[(&str, EpicStatus)] = &[
            ("Active Epics", EpicStatus::Active),
            ("Planned Epics", EpicStatus::Planned),
        ];

        for (label, status) in status_groups {
            let group: Vec<_> = epics
                .iter()
                .filter(|e| e.frontmatter.status == *status)
                .collect();
            if group.is_empty() {
                continue;
            }
            content.push_str(&format!("## {}\n\n", label));

            for epic in &group {
                render_epic_with_items(&mut content, epic, &tasks);
            }
        }

        // --- Done Epics ---
        let done_epics: Vec<_> = epics
            .iter()
            .filter(|e| e.frontmatter.status == EpicStatus::Done)
            .collect();
        if !done_epics.is_empty() {
            content.push_str("## Done Epics\n\n");
            for epic in &done_epics {
                render_epic_with_items(&mut content, epic, &tasks);
            }
        }

        fs::write(self.root().join("roadmap/INDEX.md"), content)?;
        Ok(())
    }

    /// Regenerate plans/INDEX.md with active/completed plans.
    pub fn generate_plans_index(&self) -> Result<()> {
        let plans = self.list_plans()?;

        let mut content = format!("{}\n# Plans Index\n\n", GENERATED_HEADER);

        // Active plans (draft, approved, in-progress)
        let active_plans: Vec<_> = plans
            .iter()
            .filter(|p| p.frontmatter.status != PlanStatus::Done)
            .collect();
        if !active_plans.is_empty() {
            content.push_str("## Active Plans\n\n");
            content.push_str("| Plan | Status | Implements |\n");
            content.push_str("|------|--------|------------|\n");
            for plan in &active_plans {
                let implements_str = if plan.frontmatter.implements.is_empty() {
                    "—".to_string()
                } else {
                    plan.frontmatter
                        .implements
                        .iter()
                        .map(|id| cross_link(id))
                        .collect::<Vec<_>>()
                        .join(", ")
                };
                content.push_str(&format!(
                    "| {} {} | {} | {} |\n",
                    item_link(&plan.frontmatter.id),
                    plan.frontmatter.title,
                    plan.frontmatter.status,
                    implements_str
                ));
            }
            content.push('\n');
        }

        // Done plans
        let done_plans: Vec<_> = plans
            .iter()
            .filter(|p| p.frontmatter.status == PlanStatus::Done)
            .collect();
        if !done_plans.is_empty() {
            content.push_str("## Completed Plans\n\n");
            for plan in &done_plans {
                content.push_str(&format!(
                    "- {} {}\n",
                    item_link(&plan.frontmatter.id), plan.frontmatter.title
                ));
            }
            content.push('\n');
        }

        fs::write(self.root().join("plans/INDEX.md"), content)?;
        Ok(())
    }

    /// Regenerate notes/INDEX.md with active notes.
    pub fn generate_notes_index(&self) -> Result<()> {
        let notes = self.list_notes()?;

        let mut content = format!("{}\n# Notes Index\n\n", GENERATED_HEADER);

        // Active/draft notes
        let active_notes: Vec<_> = notes
            .iter()
            .filter(|n| n.frontmatter.status != NoteStatus::Archived)
            .collect();
        if !active_notes.is_empty() {
            content.push_str("## Active Notes\n\n");
            content.push_str("| Note | Type | Status | Tags |\n");
            content.push_str("|------|------|--------|------|\n");
            for note in &active_notes {
                let tags_str = if note.frontmatter.tags.is_empty() {
                    "—".to_string()
                } else {
                    note.frontmatter.tags.join(", ")
                };
                content.push_str(&format!(
                    "| {} {} | {} | {} | {} |\n",
                    item_link(&note.frontmatter.id),
                    note.frontmatter.title,
                    note.frontmatter.note_type,
                    note.frontmatter.status,
                    tags_str
                ));
            }
            content.push('\n');
        }

        // Archived notes
        let archived_notes: Vec<_> = notes
            .iter()
            .filter(|n| n.frontmatter.status == NoteStatus::Archived)
            .collect();
        if !archived_notes.is_empty() {
            content.push_str("## Archived Notes\n\n");
            for note in &archived_notes {
                content.push_str(&format!(
                    "- {} {} ({})\n",
                    item_link(&note.frontmatter.id), note.frontmatter.title, note.frontmatter.note_type
                ));
            }
            content.push('\n');
        }

        // Special files
        content.push_str("## Special Files\n");
        content.push_str("- [ideas.md](ideas.md) — Quick capture\n");
        content.push_str("- [decisions.md](decisions.md) — Decision log\n");

        fs::write(self.root().join("notes/INDEX.md"), content)?;
        Ok(())
    }

    /// Regenerate all INDEX.md files.
    pub fn sync_all_indexes(&self) -> Result<()> {
        self.generate_root_index()?;
        self.generate_backlog_index()?;
        self.generate_roadmap_index()?;
        self.generate_plans_index()?;
        self.generate_notes_index()?;
        Ok(())
    }
}

/// Format an optional epic reference as a cross-directory link.
fn epic_cell(epic: &Option<String>) -> String {
    epic.as_ref()
        .map(|e| cross_link(e))
        .unwrap_or_else(|| "\u{2014}".to_string())
}

/// Format an item ID as a markdown link to its file in the same directory's items/ subdirectory.
fn item_link(id: &str) -> String {
    format!("[{}](items/{}.md)", id, id)
}

/// Format an item ID as a markdown link to its file in another directory.
/// Resolves the prefix to the correct directory (e.g. TASK-001 → ../backlog/items/TASK-001.md).
fn cross_link(id: &str) -> String {
    let dir = match id.split('-').next() {
        Some("EPIC") => "roadmap",
        Some("TASK") => "backlog",
        Some("PLAN") => "plans",
        Some("NOTE") => "notes",
        _ => return id.to_string(),
    };
    format!("[{}](../{}/items/{}.md)", id, dir, id)
}

/// Render an epic heading with its nested task table.
fn render_epic_with_items(
    content: &mut String,
    epic: &MarkplaneDocument<Epic>,
    tasks: &[MarkplaneDocument<Task>],
) {
    let epic_id = &epic.frontmatter.id;
    let (done, total) = epic_progress(epic_id, tasks);
    let pct = if total > 0 {
        (done as f64 / total as f64 * 100.0) as u32
    } else {
        0
    };
    content.push_str(&format!(
        "### {} {} ({}/{}, {}%)\n\n",
        item_link(epic_id), epic.frontmatter.title, done, total, pct
    ));

    let epic_items: Vec<_> = tasks
        .iter()
        .filter(|i| i.frontmatter.epic.as_deref() == Some(epic_id.as_str()))
        .collect();

    if epic_items.is_empty() {
        content.push_str("_No tasks._\n\n");
    } else {
        content.push_str("| ID | Title | Status | Priority | Effort |\n");
        content.push_str("|----|-------|--------|----------|--------|\n");
        for item in &epic_items {
            let fm = &item.frontmatter;
            content.push_str(&format!(
                "| {} | {} | {} | {} | {} |\n",
                cross_link(&fm.id), fm.title, fm.status, fm.priority, fm.effort
            ));
        }
        content.push('\n');
    }
}

/// Count (done, total) tasks for a given epic.
fn epic_progress(epic_id: &str, items: &[MarkplaneDocument<Task>]) -> (usize, usize) {
    let epic_items: Vec<_> = items
        .iter()
        .filter(|i| i.frontmatter.epic.as_deref() == Some(epic_id))
        .collect();
    let total = epic_items.len();
    let done = epic_items
        .iter()
        .filter(|i| i.frontmatter.status == TaskStatus::Done)
        .count();
    (done, total)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn setup_project() -> (TempDir, Project) {
        let tmp = TempDir::new().unwrap();
        let root = tmp.path().join(".markplane");
        let project = Project::init(root, "Test Project", "A test project").unwrap();
        (tmp, project)
    }

    #[test]
    fn test_generate_root_index_empty() {
        let (_tmp, project) = setup_project();
        project.generate_root_index().unwrap();
        let content = fs::read_to_string(project.root().join("INDEX.md")).unwrap();
        assert!(content.contains(GENERATED_HEADER));
        assert!(content.contains("Markplane Project Index"));
        assert!(content.contains("0 active epics"));
        assert!(content.contains("0 open items"));
        assert!(content.contains("Last sync:"));
    }

    #[test]
    fn test_generate_root_index_with_items() {
        let (_tmp, project) = setup_project();
        project.create_epic("Phase 1", Priority::High).unwrap();
        project
            .create_task(
                "Item 1",
                ItemType::Feature,
                Priority::High,
                Effort::Medium,
                None,
                vec![],
            )
            .unwrap();
        project.generate_root_index().unwrap();

        let content = fs::read_to_string(project.root().join("INDEX.md")).unwrap();
        assert!(content.contains("1 active epics"));
        assert!(content.contains("1 open items"));
    }

    #[test]
    fn test_generate_backlog_index_empty() {
        let (_tmp, project) = setup_project();
        project.generate_backlog_index().unwrap();
        let content = fs::read_to_string(project.root().join("backlog/INDEX.md")).unwrap();
        assert!(content.contains(GENERATED_HEADER));
        assert!(content.contains("Backlog Index"));
        assert!(content.contains("## In Progress (0)"));
        assert!(content.contains("## Blocked (0)"));
        assert!(content.contains("## Planned (0)"));
        assert!(content.contains("## Backlog (0)"));
        assert!(content.contains("## Drafts (0)"));
    }

    #[test]
    fn test_generate_backlog_index_groups_by_status() {
        let (_tmp, project) = setup_project();
        let draft_task = project
            .create_task(
                "Draft item",
                ItemType::Feature,
                Priority::Medium,
                Effort::Small,
                None,
                vec![],
            )
            .unwrap();
        let progress_task = project
            .create_task(
                "Progress item",
                ItemType::Bug,
                Priority::High,
                Effort::Medium,
                None,
                vec![],
            )
            .unwrap();
        project.update_status(&progress_task.id, "in-progress").unwrap();

        project.generate_backlog_index().unwrap();
        let content = fs::read_to_string(project.root().join("backlog/INDEX.md")).unwrap();
        assert!(content.contains("## In Progress (1)"));
        assert!(content.contains("## Drafts (1)"));
        assert!(content.contains(&format!("[{}](items/{}.md)", progress_task.id, progress_task.id)));
        assert!(content.contains(&format!("[{}](items/{}.md)", draft_task.id, draft_task.id)));
    }

    #[test]
    fn test_generate_backlog_index_sorted_by_priority() {
        let (_tmp, project) = setup_project();
        let med_task = project
            .create_task(
                "Medium 1",
                ItemType::Feature,
                Priority::Medium,
                Effort::Small,
                None,
                vec![],
            )
            .unwrap();
        let high1_task = project
            .create_task(
                "High 1",
                ItemType::Feature,
                Priority::High,
                Effort::Small,
                None,
                vec![],
            )
            .unwrap();
        project
            .create_task(
                "High 2",
                ItemType::Feature,
                Priority::High,
                Effort::Small,
                None,
                vec![],
            )
            .unwrap();

        project.generate_backlog_index().unwrap();
        let content = fs::read_to_string(project.root().join("backlog/INDEX.md")).unwrap();
        assert!(content.contains("## Drafts (3)"));
        // High items should appear before medium (sorted by list_tasks)
        let high1_link = format!("[{}](items/{}.md)", high1_task.id, high1_task.id);
        let med_link = format!("[{}](items/{}.md)", med_task.id, med_task.id);
        let high1_pos = content.find(&high1_link).unwrap();
        let med_pos = content.find(&med_link).unwrap();
        assert!(
            high1_pos < med_pos,
            "High priority items should come before medium"
        );
    }

    #[test]
    fn test_generate_backlog_index_shows_epic_column() {
        let (_tmp, project) = setup_project();
        let epic = project.create_epic("Phase 1", Priority::High).unwrap();
        project
            .create_task(
                "Item in epic",
                ItemType::Feature,
                Priority::High,
                Effort::Medium,
                Some(epic.id.clone()),
                vec![],
            )
            .unwrap();
        project
            .create_task(
                "Orphan item",
                ItemType::Feature,
                Priority::Medium,
                Effort::Small,
                None,
                vec![],
            )
            .unwrap();

        project.generate_backlog_index().unwrap();
        let content = fs::read_to_string(project.root().join("backlog/INDEX.md")).unwrap();
        assert!(content.contains(&format!("[{}](../roadmap/items/{}.md)", epic.id, epic.id)));
        assert!(content.contains("\u{2014}"));
    }

    #[test]
    fn test_generate_backlog_index_blocked_section() {
        let (_tmp, project) = setup_project();
        let blocker = project
            .create_task(
                "Blocker",
                ItemType::Feature,
                Priority::High,
                Effort::Small,
                None,
                vec![],
            )
            .unwrap();
        let blocked = project
            .create_task(
                "Blocked item",
                ItemType::Feature,
                Priority::High,
                Effort::Medium,
                None,
                vec![],
            )
            .unwrap();

        // Set blocked task to depend on blocker
        let mut doc: MarkplaneDocument<Task> = project.read_item(&blocked.id).unwrap();
        doc.frontmatter.depends_on = vec![blocker.id.clone()];
        project.write_item(&blocked.id, &doc).unwrap();

        project.generate_backlog_index().unwrap();
        let content = fs::read_to_string(project.root().join("backlog/INDEX.md")).unwrap();
        assert!(content.contains("## Blocked (1)"));
        assert!(content.contains(&format!("[{}](../backlog/items/{}.md)", blocker.id, blocker.id))); // In the Blocked By column
        // blocker is in Drafts (not blocked), blocked task is in Blocked
        assert!(content.contains("## Drafts (1)"));
    }

    #[test]
    fn test_generate_backlog_index_recently_done() {
        let (_tmp, project) = setup_project();
        let done_task = project
            .create_task(
                "Done item",
                ItemType::Feature,
                Priority::High,
                Effort::Small,
                None,
                vec![],
            )
            .unwrap();
        project
            .create_task(
                "Still open",
                ItemType::Feature,
                Priority::Medium,
                Effort::Small,
                None,
                vec![],
            )
            .unwrap();
        project.update_status(&done_task.id, "done").unwrap();

        project.generate_backlog_index().unwrap();
        let content = fs::read_to_string(project.root().join("backlog/INDEX.md")).unwrap();
        assert!(content.contains("## Recently Done (1)"));
        assert!(content.contains(&format!("[{}](items/{}.md)", done_task.id, done_task.id)));
        // The open item should be in Drafts, not in Recently Done
        assert!(content.contains("## Drafts (1)"));
    }

    #[test]
    fn test_generate_backlog_index_no_recently_done_when_empty() {
        let (_tmp, project) = setup_project();
        project
            .create_task(
                "Open item",
                ItemType::Feature,
                Priority::Medium,
                Effort::Small,
                None,
                vec![],
            )
            .unwrap();

        project.generate_backlog_index().unwrap();
        let content = fs::read_to_string(project.root().join("backlog/INDEX.md")).unwrap();
        assert!(!content.contains("Recently Done"));
    }

    #[test]
    fn test_generate_roadmap_index() {
        let (_tmp, project) = setup_project();
        let active_epic = project.create_epic("Active Epic", Priority::High).unwrap();
        project.update_status(&active_epic.id, "active").unwrap();
        let planned_epic = project
            .create_epic("Planned Epic", Priority::Medium)
            .unwrap();

        // Add a task linked to the active epic
        let task = project
            .create_task(
                "Item 1",
                ItemType::Feature,
                Priority::High,
                Effort::Medium,
                Some(active_epic.id.clone()),
                vec![],
            )
            .unwrap();

        project.generate_roadmap_index().unwrap();
        let content = fs::read_to_string(project.root().join("roadmap/INDEX.md")).unwrap();
        assert!(content.contains(GENERATED_HEADER));
        assert!(content.contains("## Active Epics"));
        assert!(content.contains(&format!("### [{}](items/{}.md) Active Epic (0/1, 0%)", active_epic.id, active_epic.id)));
        assert!(content.contains(&format!("[{}](../backlog/items/{}.md)", task.id, task.id)));
        assert!(content.contains("## Planned Epics"));
        assert!(content.contains(&format!("### [{}](items/{}.md) Planned Epic (0/0, 0%)", planned_epic.id, planned_epic.id)));
    }

    #[test]
    fn test_generate_roadmap_index_epic_with_items_table() {
        let (_tmp, project) = setup_project();
        let epic = project.create_epic("Test Epic", Priority::High).unwrap();
        project.update_status(&epic.id, "active").unwrap();

        let task_a = project
            .create_task(
                "Task A",
                ItemType::Feature,
                Priority::High,
                Effort::Small,
                Some(epic.id.clone()),
                vec![],
            )
            .unwrap();
        let task_b = project
            .create_task(
                "Task B",
                ItemType::Bug,
                Priority::Medium,
                Effort::Medium,
                Some(epic.id.clone()),
                vec![],
            )
            .unwrap();
        project.update_status(&task_a.id, "done").unwrap();

        project.generate_roadmap_index().unwrap();
        let content = fs::read_to_string(project.root().join("roadmap/INDEX.md")).unwrap();
        assert!(content.contains(&format!("### [{}](items/{}.md) Test Epic (1/2, 50%)", epic.id, epic.id)));
        assert!(content.contains("| ID | Title | Status | Priority | Effort |"));
        assert!(content.contains(&format!("[{}](../backlog/items/{}.md)", task_a.id, task_a.id)));
        assert!(content.contains(&format!("[{}](../backlog/items/{}.md)", task_b.id, task_b.id)));
    }

    #[test]
    fn test_generate_roadmap_index_done_epics() {
        let (_tmp, project) = setup_project();
        let done_epic = project.create_epic("Done Epic", Priority::High).unwrap();
        let task_a = project
            .create_task(
                "Task A",
                ItemType::Feature,
                Priority::High,
                Effort::Small,
                Some(done_epic.id.clone()),
                vec![],
            )
            .unwrap();
        project.update_status(&task_a.id, "done").unwrap();
        project.update_status(&done_epic.id, "done").unwrap();

        let active_epic = project
            .create_epic("Active Epic", Priority::Medium)
            .unwrap();
        project.update_status(&active_epic.id, "active").unwrap();

        project.generate_roadmap_index().unwrap();
        let content = fs::read_to_string(project.root().join("roadmap/INDEX.md")).unwrap();
        assert!(content.contains("## Done Epics"));
        assert!(content.contains("Done Epic (1/1, 100%)"));
        assert!(content.contains("## Active Epics"));
        assert!(content.contains("Active Epic"));
    }

    #[test]
    fn test_generate_roadmap_index_no_done_section_when_empty() {
        let (_tmp, project) = setup_project();
        project.create_epic("Planned Epic", Priority::High).unwrap();

        project.generate_roadmap_index().unwrap();
        let content = fs::read_to_string(project.root().join("roadmap/INDEX.md")).unwrap();
        assert!(!content.contains("Done Epics"));
    }

    #[test]
    fn test_generate_plans_index() {
        let (_tmp, project) = setup_project();
        // Create a task first so the implements reference is valid
        let task = project
            .create_task(
                "Some task",
                ItemType::Feature,
                Priority::Medium,
                Effort::Medium,
                None,
                vec![],
            )
            .unwrap();
        let active_plan = project
            .create_plan("Active Plan", vec![task.id.clone()], None)
            .unwrap();
        let done_plan = project.create_plan("Done Plan", vec![], None).unwrap();
        project.update_status(&done_plan.id, "done").unwrap();

        project.generate_plans_index().unwrap();
        let content = fs::read_to_string(project.root().join("plans/INDEX.md")).unwrap();
        assert!(content.contains("Active Plans"));
        assert!(content.contains(&format!("[{}](items/{}.md)", active_plan.id, active_plan.id)));
        assert!(content.contains(&format!("[{}](../backlog/items/{}.md)", task.id, task.id)));
        assert!(content.contains("Completed Plans"));
        assert!(content.contains(&format!("[{}](items/{}.md)", done_plan.id, done_plan.id)));
    }

    #[test]
    fn test_generate_notes_index() {
        let (_tmp, project) = setup_project();
        let note_a = project
            .create_note("Research A", NoteType::Research, vec!["cache".to_string()])
            .unwrap();
        project
            .create_note("Analysis B", NoteType::Analysis, vec![])
            .unwrap();

        project.generate_notes_index().unwrap();
        let content = fs::read_to_string(project.root().join("notes/INDEX.md")).unwrap();
        assert!(content.contains(GENERATED_HEADER));
        assert!(content.contains("Active Notes"));
        assert!(content.contains(&format!("[{}](items/{}.md)", note_a.id, note_a.id)));
        assert!(content.contains("cache"));
        assert!(content.contains("Special Files"));
        assert!(content.contains("ideas.md"));
    }

    #[test]
    fn test_sync_all_indexes() {
        let (_tmp, project) = setup_project();
        let epic = project.create_epic("Phase 1", Priority::High).unwrap();
        project
            .create_task(
                "Item 1",
                ItemType::Feature,
                Priority::High,
                Effort::Medium,
                Some(epic.id.clone()),
                vec![],
            )
            .unwrap();

        project.sync_all_indexes().unwrap();

        // All index files should exist and be generated
        assert!(fs::read_to_string(project.root().join("INDEX.md"))
            .unwrap()
            .contains(GENERATED_HEADER));
        assert!(fs::read_to_string(project.root().join("backlog/INDEX.md"))
            .unwrap()
            .contains(GENERATED_HEADER));
        assert!(fs::read_to_string(project.root().join("roadmap/INDEX.md"))
            .unwrap()
            .contains(GENERATED_HEADER));
        assert!(fs::read_to_string(project.root().join("plans/INDEX.md"))
            .unwrap()
            .contains(GENERATED_HEADER));
        assert!(fs::read_to_string(project.root().join("notes/INDEX.md"))
            .unwrap()
            .contains(GENERATED_HEADER));
    }

    #[test]
    fn test_generate_root_index_no_kb_row() {
        let (_tmp, project) = setup_project();
        project.generate_root_index().unwrap();
        let content = fs::read_to_string(project.root().join("INDEX.md")).unwrap();
        assert!(!content.contains("Knowledge Base"));
        assert!(!content.contains("kb/"));
    }

    #[test]
    fn test_generate_root_index_with_documentation() {
        let (tmp, project) = setup_project();
        let docs_dir = tmp.path().join("docs");
        fs::create_dir_all(&docs_dir).unwrap();
        fs::write(docs_dir.join("architecture.md"), "# Architecture").unwrap();

        let mut config = project.load_config().unwrap();
        config.documentation_paths = vec!["docs".to_string()];
        project.save_config(&config).unwrap();

        project.generate_root_index().unwrap();
        let content = fs::read_to_string(project.root().join("INDEX.md")).unwrap();
        assert!(content.contains("## Project Documentation"));
        assert!(content.contains("architecture"));
        assert!(content.contains("../docs/architecture.md"));
    }

    #[test]
    fn test_generate_root_index_no_documentation_section_when_empty() {
        let (_tmp, project) = setup_project();
        project.generate_root_index().unwrap();
        let content = fs::read_to_string(project.root().join("INDEX.md")).unwrap();
        assert!(!content.contains("Project Documentation"));
    }
}
