/// Fractional indexing utilities for persistent manual ordering.
///
/// Generates position keys compatible with the `fractional-indexing` npm package
/// (Rocicorp). Keys are lexicographically sortable base-62 strings.
///
/// Format: integer part (prefix char + digits) + optional fractional part.
/// - `a` prefix = 1 digit (values 0–61): a0, a1, ..., az
/// - `b` prefix = 2 digits (values 62–3905): b00, b01, ..., bzz
const DIGITS: &[u8] = b"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

/// Generate N sequential position keys for sync normalization.
///
/// Produces clean, short keys: "a0", "a1", ..., "az", "b00", "b01", ...
/// These are valid keys in the Rocicorp fractional-indexing format.
pub fn sequential_keys(n: usize) -> Vec<String> {
    let mut keys = Vec::with_capacity(n);
    for i in 0..n {
        keys.push(index_to_key(i));
    }
    keys
}

pub fn index_to_key(i: usize) -> String {
    if i < 62 {
        format!("a{}", DIGITS[i] as char)
    } else {
        let i2 = i - 62;
        let d1 = i2 / 62;
        let d0 = i2 % 62;
        debug_assert!(d1 < 62, "position index too large for 2-digit encoding");
        format!("b{}{}", DIGITS[d1] as char, DIGITS[d0] as char)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_sequential_keys_basic() {
        let keys = sequential_keys(5);
        assert_eq!(keys, vec!["a0", "a1", "a2", "a3", "a4"]);
    }

    #[test]
    fn test_sequential_keys_ordering() {
        let keys = sequential_keys(100);
        for i in 1..keys.len() {
            assert!(
                keys[i - 1] < keys[i],
                "keys not ordered: {} >= {}",
                keys[i - 1],
                keys[i]
            );
        }
    }

    #[test]
    fn test_sequential_keys_boundary() {
        let keys = sequential_keys(65);
        // Last single-digit key
        assert_eq!(keys[61], "az");
        // First two-digit key
        assert_eq!(keys[62], "b00");
        assert_eq!(keys[63], "b01");
        assert_eq!(keys[64], "b02");
    }

    #[test]
    fn test_sequential_keys_empty() {
        let keys = sequential_keys(0);
        assert!(keys.is_empty());
    }

    #[test]
    fn test_fractional_key_sorts_between() {
        // Verify that a fractional key generated by the npm package
        // (e.g., "a0V" between "a0" and "a1") sorts correctly
        let a0 = "a0";
        let fractional = "a0V";
        let a1 = "a1";
        assert!(a0 < fractional);
        assert!(fractional < a1);
    }
}
